### ISSUE TITLE
MQTT authentication

### ISSUE THREAD

**Issue by christianTF** [terafin/mqtt-tesla-bridge#23]
Hi,

is it possible to set env vars to authenticate to the mqtt broker?
My broker requires user/pass auth on the 1883 mqtt port.

Thanks in advance for your response!
Christian

**Comment by terafin** [comment]
This is supported, but poorly documented :) I'll fix that today!

**Comment by terafin** [comment]
Should be resolved by: https://github.com/terafin/mqtt-tesla-bridge/commit/6f5ae2d3db7f9a17b4f8c8cf84fc3512f94def9a

Can you confirm please?
