### ISSUE TITLE
CONTROLLER_IP and CONTROLLER_SERIAL_NUMBER

### ISSUE THREAD

**Issue by christianTF** [terafin/mqtt-tesla-bridge#24]
Hi!

The container additionally needs CONTROLLER_IP and CONTROLLER_SERIAL_NUMBER as environment variables. This leads to me to suppose that the mqtt-tesla-bridge requires a Tesla powerwall. 
These requirements are not documented in the readme, and mistakenly I thought the repo directly can access Tesla's information.

https://github.com/terafin/mqtt-tesla-bridge/blob/7cd43d808f465983763d4eb9b3e69f86c54c8a1c/lib/tesla.js#L13

The additional requirements (Tesla powerwall, environment variables) should be documented.

**Comment by terafin** [comment]
Yup, I'll fix that presently, sorry! (Copying standard docs over from my other projects!

**Comment by terafin** [comment]
Should be resolved by: https://github.com/terafin/mqtt-tesla-bridge/commit/6f5ae2d3db7f9a17b4f8c8cf84fc3512f94def9a

can you confirm please? :)
