### ISSUE TITLE
Gateway firmware 20.49.0 requires customer auth to access any stats

### ISSUE THREAD

**Issue by pillarama** [terafin/mqtt-tesla-bridge#36]
Hi thanks very much for this great project. My gateway firmware was updated to 20.49.0 this week and my mqtt-tesla-bridge stopped working (and it reset my customised password too!! :-$ ) . After much keyboard mashing and head banging (I'm not a seasoned programmer and have never programmed in javascript before, nor know much about http requests / authentication). I managed to update the login process to use the customer authentication, get the auth token and then pass the auth token back as a cookie. It looked to me as though the existing .auth function in the nodejs request library should have just worked

 but for some reason I couldn't make it. Just kept getting "token contains an invalid number of segments". Defining a cookie the only way I've been able to get it to work...

In case it's helpful here is a patch for reference as to what I did, but I'd say this definitely should be checked carefully by someone more experienced than me before it's merged.
[cust-auth.diff.txt](https://github.com/terafin/mqtt-tesla-bridge/files/6028551/cust-auth.diff.txt)
Thanks

Charles

**Comment by terafin** [comment]
Thank you @pillarama , taking a look at this now!

**Comment by terafin** [comment]
This should be now complete, thanks @pillarama ! Updating docs...
